'use client'

import { useState } from 'react'
import { FileText, Copy, Download, Mail, Phone, Shield } from 'lucide-react'
import { motion } from 'framer-motion'
import toast from 'react-hot-toast'

interface ComplaintGeneratorProps {
  result: any
}

export default function ComplaintGenerator({ result }: ComplaintGeneratorProps) {
  const [userDetails, setUserDetails] = useState({
    name: '',
    phone: '',
    bank: '',
    email: ''
  })
  const [showForm, setShowForm] = useState(false)

  const generateComplaint = () => {
    if (!userDetails.name || !userDetails.phone) {
      toast.error('Please fill in your name and phone number')
      return
    }
    setShowForm(true)
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    toast.success('Complaint copied to clipboard!')
  }

  const downloadComplaint = () => {
    const complaint = generateComplaintText()
    const blob = new Blob([complaint], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'cybercrime-complaint.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    toast.success('Complaint downloaded!')
  }

  const generateComplaintText = () => {
    const date = new Date().toLocaleDateString('en-IN')
    
    return `
CYBER CRIME COMPLAINT
=====================

Date: ${date}
Complaint ID: ${Date.now()}

COMPLAINANT DETAILS:
Name: ${userDetails.name}
Phone: ${userDetails.phone}
Email: ${userDetails.email || 'Not provided'}
Bank: ${userDetails.bank || 'Not specified'}

INCIDENT DETAILS:
Type: Digital Scam / UPI Fraud
Risk Level: ${result?.risk_level || 'Unknown'}
Analysis Result: ${result?.classification || 'Unknown'}
Confidence: ${result?.confidence_score || 'Unknown'}

RED FLAGS DETECTED:
${result?.red_flags?.map((flag: string) => `• ${flag}`).join('\n') || '• Multiple suspicious patterns detected'}

AI ANALYSIS SUMMARY:
${result?.recommended_action || 'AI analysis indicated potential scam activity'}

COMPLAINT:
I, ${userDetails.name}, hereby lodge a complaint regarding a potential digital scam that was detected by AI analysis. The content analyzed showed multiple red flags indicating a high risk of fraud.

The analysis revealed:
- Risk Classification: ${result?.classification || 'Unknown'}
- Confidence Level: ${result?.confidence_score || 'Unknown'}
- Multiple suspicious patterns and keywords

I request immediate investigation and action to prevent potential victims from falling prey to this scam.

CONTACT INFORMATION:
Phone: ${userDetails.phone}
Email: ${userDetails.email || 'Not provided'}

I am available for any additional information or clarification required for this investigation.

Yours faithfully,
${userDetails.name}
${userDetails.phone}

---
Generated by UPI Scam Checker v3.0.0
Report to: cybercrime.gov.in
`
  }

  return (
    <div className="card">
      <div className="mb-6">
        <h3 className="text-xl font-semibold text-gray-900 mb-2">
          📝 Cyber Crime Complaint Generator
        </h3>
        <p className="text-gray-600">
          Generate a formal complaint for cyber crime reporting based on your analysis results.
        </p>
      </div>

      {!showForm ? (
        <div className="space-y-4">
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <h4 className="font-semibold text-blue-800 mb-2">📊 Analysis Summary</h4>
            <div className="text-sm text-blue-700 space-y-1">
              <p><strong>Classification:</strong> {result?.classification || 'Unknown'}</p>
              <p><strong>Risk Level:</strong> {result?.risk_level || 'Unknown'}</p>
              <p><strong>Confidence:</strong> {result?.confidence_score || 'Unknown'}</p>
            </div>
          </div>

          <button
            onClick={generateComplaint}
            className="w-full bg-red-600 text-white py-3 px-4 rounded-lg hover:bg-red-700 transition-colors flex items-center justify-center space-x-2"
          >
            <FileText className="h-5 w-5" />
            <span>Generate Complaint</span>
          </button>
        </div>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
              Full Name *
            </label>
            <input
              type="text"
              id="name"
              value={userDetails.name}
              onChange={(e) => setUserDetails({...userDetails, name: e.target.value})}
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              required
            />
          </div>

          <div>
            <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-2">
              Phone Number *
            </label>
            <input
              type="tel"
              id="phone"
              value={userDetails.phone}
              onChange={(e) => setUserDetails({...userDetails, phone: e.target.value})}
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              required
            />
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
              Email Address
            </label>
            <input
              type="email"
              id="email"
              value={userDetails.email}
              onChange={(e) => setUserDetails({...userDetails, email: e.target.value})}
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <div>
            <label htmlFor="bank" className="block text-sm font-medium text-gray-700 mb-2">
              Bank Name (if applicable)
            </label>
            <input
              type="text"
              id="bank"
              value={userDetails.bank}
              onChange={(e) => setUserDetails({...userDetails, bank: e.target.value})}
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <div className="flex space-x-3">
            <button
              onClick={() => copyToClipboard(generateComplaintText())}
              className="flex-1 bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition-colors flex items-center justify-center space-x-2"
            >
              <Copy className="h-4 w-4" />
              <span>Copy</span>
            </button>
            <button
              onClick={downloadComplaint}
              className="flex-1 bg-green-600 text-white py-2 px-4 rounded-md hover:bg-green-700 transition-colors flex items-center justify-center space-x-2"
            >
              <Download className="h-4 w-4" />
              <span>Download</span>
            </button>
          </div>

          <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <h4 className="font-semibold text-yellow-800 mb-2">📞 Report to:</h4>
            <ul className="text-sm text-yellow-700 space-y-1">
              <li>• Cyber Crime Portal: <a href="https://cybercrime.gov.in" target="_blank" rel="noopener noreferrer" className="underline">cybercrime.gov.in</a></li>
              <li>• Helpline: 1930</li>
              <li>• RBI Helpline: 1800-425-3800</li>
            </ul>
          </div>
        </motion.div>
      )}
    </div>
  )
}
