'use client'

import { useState } from 'react'
import { FileText, Copy, Download, Mail, Phone, Shield } from 'lucide-react'
import { motion } from 'framer-motion'
import { AnalysisResult } from '@/app/page'
import toast from 'react-hot-toast'

interface ComplaintGeneratorProps {
  result: AnalysisResult
}

export default function ComplaintGenerator({ result }: ComplaintGeneratorProps) {
  const [userDetails, setUserDetails] = useState({
    name: '',
    phone: '',
    bank: '',
    email: ''
  })
  const [showForm, setShowForm] = useState(false)

  const generateComplaint = () => {
    if (!userDetails.name || !userDetails.phone) {
      toast.error('Please fill in your name and phone number')
      return
    }
    setShowForm(true)
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    toast.success('Complaint copied to clipboard!')
  }

  const downloadComplaint = () => {
    const complaint = generateComplaintText()
    const blob = new Blob([complaint], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'cybercrime-complaint.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    toast.success('Complaint downloaded!')
  }

  const generateComplaintText = () => {
    const date = new Date().toLocaleDateString('en-IN')
    
    return `
CYBER CRIME COMPLAINT
=====================

Date: ${date}
Complaint ID: ${Date.now()}

COMPLAINANT DETAILS:
Name: ${userDetails.name}
Phone: ${userDetails.phone}
Email: ${userDetails.email || 'Not provided'}
Bank: ${userDetails.bank || 'Not specified'}

INCIDENT DETAILS:
Type: Digital Scam / UPI Fraud
Risk Level: ${result.riskLevel}
Analysis Result: ${result.label}
Confidence: ${(result.confidence * 100).toFixed(1)}%

RED FLAGS DETECTED:
${result.redFlags.map(flag => `• ${flag}`).join('\n')}

AI ANALYSIS SUMMARY:
${result.advice}

COMPLAINT:
I, ${userDetails.name}, hereby lodge a complaint regarding a potential digital scam that was detected by AI analysis. The content analyzed showed multiple red flags indicating a high risk of fraud.

The analysis revealed:
- Risk Classification: ${result.label}
- Confidence Level: ${(result.confidence * 100).toFixed(1)}%
- Multiple suspicious patterns and keywords

I request immediate investigation and action to prevent potential victims from falling prey to this scam.

CONTACT INFORMATION:
Phone: ${userDetails.phone}
Email: ${userDetails.email || 'Not provided'}

I am available for any additional information or clarification required for this investigation.

Yours faithfully,
${userDetails.name}
${userDetails.phone}

---
Generated by UPI Scam Checker
Report to: cybercrime.gov.in
Helpline: 1930
    `.trim()
  }

  const generateBankDispute = () => {
    const date = new Date().toLocaleDateString('en-IN')
    
    return `
BANK DISPUTE EMAIL
==================

Subject: Dispute Report - Potential UPI Scam

Dear Sir/Madam,

I am writing to report a potential UPI scam that was detected through AI analysis.

CUSTOMER DETAILS:
Account Holder: ${userDetails.name}
Phone Number: ${userDetails.phone}
Email: ${userDetails.email || 'Not provided'}

INCIDENT DETAILS:
Date: ${date}
Type: Potential UPI Scam
Risk Level: ${result.riskLevel}

AI ANALYSIS RESULTS:
The suspicious content was analyzed using advanced AI technology and classified as:
- Risk Level: ${result.label}
- Confidence: ${(result.confidence * 100).toFixed(1)}%
- Red Flags: ${result.redFlags.length} suspicious patterns detected

RED FLAGS IDENTIFIED:
${result.redFlags.map(flag => `• ${flag}`).join('\n')}

RECOMMENDED ACTION:
${result.advice}

I request your bank to:
1. Investigate this potential scam
2. Take necessary preventive measures
3. Alert other customers if similar patterns are detected
4. Provide guidance on additional security measures

I am available for any additional information or documentation required.

Please acknowledge receipt of this complaint and provide a reference number for follow-up.

Yours sincerely,
${userDetails.name}
${userDetails.phone}

---
Generated by UPI Scam Checker
    `.trim()
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="card border-2 border-red-200 bg-red-50"
    >
      <div className="flex items-center space-x-3 mb-4">
        <FileText className="h-6 w-6 text-red-600" />
        <h3 className="text-xl font-semibold text-red-900">
          Generate Complaint
        </h3>
      </div>
      
      <p className="text-red-800 mb-6">
        Since this content was classified as high-risk, we can help you generate formal complaints 
        for cyber crime authorities and your bank. This will help protect others from similar scams.
      </p>

      {!showForm ? (
        <button
          onClick={generateComplaint}
          className="btn-primary w-full"
        >
          Generate Complaint Documents
        </button>
      ) : (
        <div className="space-y-6">
          {/* User Details Form */}
          <div className="bg-white p-4 rounded-lg border border-gray-200">
            <h4 className="font-semibold text-gray-900 mb-3">Your Details</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Full Name *
                </label>
                <input
                  type="text"
                  value={userDetails.name}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, name: e.target.value }))}
                  className="input-field"
                  placeholder="Enter your full name"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Phone Number *
                </label>
                <input
                  type="tel"
                  value={userDetails.phone}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, phone: e.target.value }))}
                  className="input-field"
                  placeholder="Enter your phone number"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Email Address
                </label>
                <input
                  type="email"
                  value={userDetails.email}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, email: e.target.value }))}
                  className="input-field"
                  placeholder="Enter your email (optional)"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Bank Name
                </label>
                <input
                  type="text"
                  value={userDetails.bank}
                  onChange={(e) => setUserDetails(prev => ({ ...prev, bank: e.target.value }))}
                  className="input-field"
                  placeholder="Enter your bank name (optional)"
                />
              </div>
            </div>
          </div>

          {/* Generated Complaints */}
          <div className="space-y-4">
            {/* Cyber Crime Complaint */}
            <div className="bg-white p-4 rounded-lg border border-gray-200">
              <h4 className="font-semibold text-gray-900 mb-3 flex items-center">
                <Shield className="h-5 w-5 text-primary-500 mr-2" />
                Cyber Crime Complaint
              </h4>
              <div className="bg-gray-50 p-3 rounded border text-sm text-gray-700 mb-3 max-h-32 overflow-y-auto">
                {generateComplaintText()}
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => copyToClipboard(generateComplaintText())}
                  className="btn-secondary flex items-center space-x-2"
                >
                  <Copy className="h-4 w-4" />
                  <span>Copy</span>
                </button>
                <button
                  onClick={downloadComplaint}
                  className="btn-secondary flex items-center space-x-2"
                >
                  <Download className="h-4 w-4" />
                  <span>Download</span>
                </button>
              </div>
            </div>

            {/* Bank Dispute Email */}
            <div className="bg-white p-4 rounded-lg border border-gray-200">
              <h4 className="font-semibold text-gray-900 mb-3 flex items-center">
                <Mail className="h-5 w-5 text-primary-500 mr-2" />
                Bank Dispute Email
              </h4>
              <div className="bg-gray-50 p-3 rounded border text-sm text-gray-700 mb-3 max-h-32 overflow-y-auto">
                {generateBankDispute()}
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => copyToClipboard(generateBankDispute())}
                  className="btn-secondary flex items-center space-x-2"
                >
                  <Copy className="h-4 w-4" />
                  <span>Copy</span>
                </button>
                <button
                  onClick={() => {
                    const dispute = generateBankDispute()
                    const blob = new Blob([dispute], { type: 'text/plain' })
                    const url = URL.createObjectURL(blob)
                    const a = document.createElement('a')
                    a.href = url
                    a.download = 'bank-dispute-email.txt'
                    document.body.appendChild(a)
                    a.click()
                    document.body.removeChild(a)
                    URL.revokeObjectURL(url)
                    toast.success('Bank dispute email downloaded!')
                  }}
                  className="btn-secondary flex items-center space-x-2"
                >
                  <Download className="h-4 w-4" />
                  <span>Download</span>
                </button>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-3">
            <a
              href="https://cybercrime.gov.in"
              target="_blank"
              rel="noopener noreferrer"
              className="btn-primary flex items-center space-x-2"
            >
              <Shield className="h-4 w-4" />
              <span>Submit to Cyber Crime Portal</span>
            </a>
            
            <a
              href="tel:1930"
              className="btn-secondary flex items-center space-x-2"
            >
              <Phone className="h-4 w-4" />
              <span>Call Helpline: 1930</span>
            </a>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="font-medium text-blue-900 mb-2">📋 Next Steps:</h4>
            <ol className="text-sm text-blue-800 space-y-1 list-decimal list-inside">
              <li>Copy or download the complaint documents</li>
              <li>Submit the cyber crime complaint to cybercrime.gov.in</li>
              <li>Send the bank dispute email to your bank's fraud department</li>
              <li>Keep copies of all communications for your records</li>
              <li>Follow up with authorities if needed</li>
            </ol>
          </div>
        </div>
      )}
    </motion.div>
  )
}
